version: "3.8"

services:
  # Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: fondazione-crm-postgres-prod
    env_file:
      - ../.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - crm-network
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: ../backend/api-gateway
      dockerfile: Dockerfile.dev
    container_name: fondazione-crm-api-gateway-prod
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - postgres
      - auth-service
      - patient-service
      - clinical-service
      - group-service
    networks:
      - crm-network
    restart: unless-stopped

  # Auth Service
  auth-service:
    build:
      context: ../backend/services/auth
      dockerfile: Dockerfile.prod
    container_name: fondazione-crm-auth-service-prod
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - postgres
    networks:
      - crm-network
    restart: unless-stopped

  # Patient Service
  patient-service:
    build:
      context: ../backend/services/patient
      dockerfile: Dockerfile.prod
    container_name: fondazione-crm-patient-service-prod
    ports:
      - "3002:3002"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3002
    depends_on:
      - postgres
    networks:
      - crm-network
    restart: unless-stopped

  # Clinical Service
  clinical-service:
    build:
      context: ../backend/services/clinical
      dockerfile: Dockerfile.prod
    container_name: fondazione-crm-clinical-service-prod
    ports:
      - "3003:3003"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3003
    depends_on:
      - postgres
    networks:
      - crm-network
    restart: unless-stopped

  # Group Service
  group-service:
    build:
      context: ../backend/services/group
      dockerfile: Dockerfile.prod
    container_name: fondazione-crm-group-service-prod
    ports:
      - "3004:3004"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3004
    depends_on:
      - postgres
    networks:
      - crm-network
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: fondazione-crm-frontend-prod
    ports:
      - "80:80"
    env_file:
      - ../.env
    depends_on:
      - api-gateway
    networks:
      - crm-network
    restart: unless-stopped

volumes:
  postgres_data_prod:

networks:
  crm-network:
    driver: bridge
